---

- hosts: all
  become: true
  tasks:
  
  - name: install apache package & add php support for Ubuntu& update repository
    apt:
      name:
        - apache2
        - libapache2-mod-php
      state: latest
      update_cache: yes
    when: ansible_distribution is ["Debian","Ubuntu"] 
  
  - name: install apache package & add php support for CentOS & update repository
    dnf:
      name:
        - httpd
        - php
      state: latest
      update_cache: yes
    when: ansible_distribution == "CentOS"
